---
- name : install nginx and start
  hosts: all
  become: true
  tasks:
    - name: install
      apt:
        name: nginx
        state: present
    - name: start
      service:
        name: nginx
        state: started

